import logo from "../assets/logo.svg";
import signIn from "../assets/signin.png";
import userIcon from "../assets/userIcon.png";
import auditIcon from "../assets/auditIcon.png";
import dashBIcon from "../assets/dashBicon.svg";
import decisionIcon from "../assets/decisionIcon.png";
import feesIcon from "../assets/feesIcon.png";
import feesPricIcon from "../assets/feesPricIcon.png";
import gaurantorIcon from "../assets/guarantorIcon.png";
import karmaIcon from "../assets/karmaIcon.png";
import loanIcon from "../assets/laonIcon.png";
import loanRqIcon from "../assets/loanRqIcon.png";
import orgIcon from "../assets/orgIcon.png";
import pigysavingIcon from "../assets/pigysavingIcon.png";
import prefIcon from "../assets/prefIcon.png";
import reportIcon from "../assets/reportIcon.png";
import savingPDTIcon from "../assets/savingPDTIcon.png";
import serviceAccIcon from "../assets/serviceAccIcon.png";
import servicesIcon from "../assets/servicesIcon.png";
import settlemntIcon from "../assets/settlemntIcon.png";
import trancIcon from "../assets/trancIcon.png";
import wishLstIcon from "../assets/wishLstIcon.png";
import searchBar from "../assets/search-bar.svg";
import dropDicon from "../assets/dropDIcon.svg";
import notification from "../assets/notification.svg";
import avatar from "../assets/avatar.png";
import profileDrop from "../assets/dropdown.svg";
import hUsersIcon from "../assets/hUsersIcon.svg";
import UserswtLoanIcon from "../assets/UserswtLoanIcon.svg";
import UserswtSaving from "../assets/UserswtSaving.svg";
import ActiveuserIcon from "../assets/ActiveuserIcon.svg";
import emptyStar from "../assets/empty-star.svg";
import filledStar from "../assets/filled-star.svg";
import verticalMore from "../assets/vertical-more.svg";

export const LOGO = logo;
export const ILLUSTRATION = signIn;
export const USERICON = userIcon;
export const AUDITICON = auditIcon;
export const DASHBICON = dashBIcon;
export const DECISIONICON = decisionIcon;
export const FEESICON = feesIcon;
export const FEESPRICICON = feesPricIcon;
export const GUARANTORICON = gaurantorIcon;
export const KARMAICON = karmaIcon;
export const LOANICON = loanIcon;
export const LAONRQICON = loanRqIcon;
export const ORGICON = orgIcon;
export const PIGYSAVINGICON = pigysavingIcon;
export const PREFICON = prefIcon;
export const REPORTICON = reportIcon;
export const SAVINGPDTICON = savingPDTIcon;
export const SERVICESACCICON = serviceAccIcon;
export const SERVICESICON = servicesIcon;
export const SETTLEMNTICON = settlemntIcon;
export const TRANCICON = trancIcon;
export const WISHLSTICON = wishLstIcon;
export const SEARCHBAR = searchBar;
export const DROPDICON = dropDicon;
export const NOTIFICATION = notification;
export const AVATAR = avatar;
export const PROFILEDROP = profileDrop;
export const USERS = hUsersIcon;
export const USERSWITHLOANS = UserswtLoanIcon;
export const USERSWITHSAVINGS = UserswtSaving;
export const ACTIVEUSERSWITHLOAN = ActiveuserIcon;
export const FILLEDSTAR = filledStar;
export const EMPTYSTAR = emptyStar;
export const VERTICALMORE = verticalMore;
